agent_name: dbc_aug
discrete_actions: false

agent:
  _target_: agents.dbc.DBCAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  transition_model_type: probabilistic
  device: ${device}
  lr: ${lr}
  beta: 0.9
  alpha_lr: 0.1
  alpha_beta: 0.5
  init_temperature: 0.01
  actor_log_std_min: -10
  actor_log_std_max: 2
  actor_update_freq: 2
  critic_target_tau: 0.01
  critic_target_update_freq: 2
  encoder_tau: 0.05
  weight_lambda: 1e-7
  num_expl_steps: 2000
  hidden_dim: 256
  feature_dim: ${feature_dim}
  bisim_coef: 0.5
  linear_approx: ${linear_approx}
  use_aug: true
