agent_name: ddpg_original
discrete_actions: false

agent:
  _target_: agents.ddpg.DDPGAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 1
  num_expl_steps: 2000
  hidden_dim: 256
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  clipped_noise: false
  linear_approx: ${linear_approx}
