agent_name: hpg
discrete_actions: false

agent:
  _target_: agents.hpg.HPGAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  abstraction_type: base
  hpg_update_type: double_add
  transition_model_type: probabilistic
  pixel_obs: ${pixel_obs}
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  num_expl_steps: 2000
  hidden_dim: 256
  matching_dims: ${matching_dims}
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  clipped_noise: true
  homomorphic_coef: 1
  linear_approx: ${linear_approx}
  use_aug: false
