agent_name: sacae
discrete_actions: false

agent:
  _target_: agents.sacae.SACAEAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  beta: 0.9
  alpha_lr: 0.1
  alpha_beta: 0.5
  init_temperature: 0.01
  actor_log_std_min: -10
  actor_log_std_max: 2
  actor_update_freq: 2
  critic_target_tau: 0.01
  critic_target_update_freq: 2
  encoder_tau: 0.05
  decoder_update_freq: 1
  decoder_latent_lambda: 1e-6
  decoder_weight_lambda: 1e-7
  num_expl_steps: 2000
  hidden_dim: 256
  feature_dim: ${feature_dim}
  linear_approx: ${linear_approx}
  use_aug: false